[tool.black]
line-length = 120

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37
skipsdist = True

[testenv]
whitelist_externals = pytest

[testenv:py37]
commands = pytest -p no:cacheprovider -p no:warnings -m 'not (integration)' --cov=src/ tests/
"""