# Use postgres/example user/password credentials
version: '3.1'

services:

  simplenight-api-db:
    image: simplenight-postgres:13
    volumes:
      - simplenight-db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: simplenight

volumes:
  simplenight-db:
