#!/bin/sh
DEFAULT_DEV_USER="simplenight"
DEFAULT_DEV_PW="simplenight"
DEFAULT_DEV_DB_NAME="simplenight"

psql -c "CREATE ROLE $DEFAULT_DEV_USER WITH PASSWORD '$DEFAULT_DEV_PW' LOGIN SUPERUSER"
psql -c "CREATE DATABASE $DEFAULT_DEV_DB_NAME"
psql -c "ALTER DATABASE $DEFAULT_DEV_DB_NAME OWNER TO $DEFAULT_DEV_USER"
