# Generated by Django 3.0.6 on 2020-07-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(unique=True)),
                ('iso_country_code', models.CharField(max_length=2)),
                ('location_name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('api_daily_limit', models.IntegerField()),
                ('api_burst_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sn_city_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplenight_city_id', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('provider_city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sn_hotel_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplenight_id', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('provider_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sn_images_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplenight_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_type', models.TextField(blank=True, null=True)),
                ('image_url_path', models.TextField(blank=True, null=True)),
                ('image_provider_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supplier_hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('hotel_codes', models.IntegerField(default=1)),
                ('hotel_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True)),
                ('chain_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(default='XX', max_length=2)),
                ('provider_name', models.CharField(default='HotelBeds', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pmt_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_transaction_id', models.IntegerField(null=True)),
                ('stripe_id', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[['refunded', 'refunded'], ['cancelled', 'cancelled'], ['paid', 'paid']], max_length=50)),
                ('transaction_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_transaction', to='api.pmt_transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='GeonameAlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_name_id', models.IntegerField()),
                ('iso_language_code', models.CharField(max_length=2)),
                ('name', models.TextField()),
                ('is_colloquial', models.BooleanField()),
                ('iatacode', models.CharField(max_length=3)),
                ('geoname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='api.Geoname', to_field='geoname_id')),
            ],
        ),
    ]
