# Generated by Django 3.0.6 on 2020-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_transaction_id', models.IntegerField(null=True)),
                ('provider_name', models.CharField(max_length=32)),
                ('charge_id', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[('refunded', 'refunded'), ('cancelled', 'cancelled'), ['paid', 'paid']], max_length=50)),
                ('transaction_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pmt_transaction',
            },
        ),
        migrations.DeleteModel(
            name='pmt_transaction',
        ),
    ]
