# Generated by Django 3.0.6 on 2020-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200805_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_status',
            field=models.CharField(max_length=50),
        ),
    ]
