# Generated by Django 3.0.6 on 2020-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200805_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_token',
            field=models.CharField(default='pt_foo', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(default='sale', max_length=12),
            preserve_default=False,
        ),
    ]
