# Generated by Django 3.0.6 on 2020-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200807_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='crs_currency',
            field=models.CharField(default="USD", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='crs_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
