# Generated by Django 3.0.6 on 2020-08-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200811_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='crs_total',
            new_name='crs_total_price',
        ),
    ]
