# Generated by Django 3.0.6 on 2020-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20200811_0729"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoname", name="population", field=models.IntegerField(default=0), preserve_default=False,
        ),
        migrations.AddField(
            model_name="geoname",
            name="province_code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geoname",
            name="timezone",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
    ]
