# Generated by Django 3.0.6 on 2020-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200814_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_hotels',
            name='state',
            field=models.CharField(default='X', max_length=2),
        ),
    ]
