# Generated by Django 3.0.6 on 2020-08-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hote_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hote_listings',
            new_name='hotel_listings',
        ),
    ]
