# Generated by Django 3.0.6 on 2020-08-21 05:16
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20200820_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityMap",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("simplenight_city_id", models.IntegerField()),
                ("provider_city_id", models.TextField()),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.Provider")),
            ],
        ),
        migrations.DeleteModel(name="sn_city_map",),
        migrations.AlterField(
            model_name="crscity",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
