# Generated by Django 3.0.6 on 2020-08-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200821_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoname',
            old_name='province_code',
            new_name='province',
        ),
    ]
