# Generated by Django 3.0.6 on 2020-08-27 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20200821_2342"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("airport_id", models.IntegerField()),
                ("airport_name", models.TextField()),
                ("city_name", models.TextField()),
                ("iso_country_code", models.TextField()),
                ("airport_code", models.CharField(max_length=3)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timezone", models.TextField()),
                (
                    "geoname",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geoname",
                        to="api.Geoname",
                        to_field="geoname_id",
                    ),
                ),
            ],
            options={"db_table": "airports",},
        ),
    ]
