# Generated by Django 3.0.6 on 2020-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_airport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['airport_name', 'airport_code'], name='airports_airport_51f186_idx'),
        ),
        migrations.AddIndex(
            model_name='geoname',
            index=models.Index(fields=['location_name'], name='api_geoname_locatio_95d21a_idx'),
        ),
        migrations.AddIndex(
            model_name='geonamealternatename',
            index=models.Index(fields=['name'], name='api_geoname_name_1211a8_idx'),
        ),
    ]
