# Generated by Django 3.0.6 on 2020-09-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200828_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrsCity',
            new_name='ProviderCity',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='crs_currency',
            new_name='provider_currency',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='crs_name',
            new_name='provider_name',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='crs_total_price',
            new_name='provider_total',
        ),
        migrations.AlterModelTable(
            name='providercity',
            table='provider_cities',
        ),
    ]
