# Generated by Django 3.0.6 on 2020-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200904_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfeatures',
            name='name',
            field=models.TextField(choices=[('enabled_connectors', 'ENABLED_ADAPTERS'), ('test_mode', 'TEST_MODE')], unique=True),
        ),
    ]
