# Generated by Django 3.0.6 on 2020-09-16 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200911_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_priceline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='Priceline', max_length=50)),
                ('supplier_id', models.CharField(blank=True, max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100)),
                ('hotel_city', models.CharField(max_length=100)),
                ('hotel_state', models.CharField(max_length=25)),
                ('hotel_country_code', models.CharField(max_length=3)),
                ('hotel_postal_code', models.CharField(max_length=15)),
                ('hotel_rating', models.FloatField()),
                ('hotel_description', models.TextField(max_length=100)),
                ('hotel_amenities', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=8), size=8)),
                ('hotelid_ppn', models.TextField(max_length=100)),
                ('cityid_ppn', models.TextField(max_length=100)),
                ('image_url_path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
