# Generated by Django 3.0.6 on 2020-09-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_supplier_priceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymap',
            name='provider_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='provider_city', to='api.ProviderCity', to_field='provider_code'),
        ),
        migrations.AlterField(
            model_name='citymap',
            name='simplenight_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='simplenight_city', to='api.Geoname', to_field='geoname_id'),
        ),
        migrations.RenameField(
            model_name='citymap',
            old_name='provider_city_id',
            new_name='provider_city',
        ),
        migrations.RenameField(
            model_name='citymap',
            old_name='simplenight_city_id',
            new_name='simplenight_city',
        ),
    ]
