# Generated by Django 3.0.6 on 2020-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200917_0718'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier_priceline',
            index=models.Index(fields=['hotelid_ppn'], name='api_supplie_hotelid_60542b_idx'),
        ),
    ]
