# Generated by Django 3.0.6 on 2020-09-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200924_0540'),
        ('api', '0003_auto_20200916_1047'),
    ]

    operations = [
    ]
