# Generated by Django 3.0.6 on 2020-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20200924_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_priceline',
            name='cityid_ppn1',
        ),
        migrations.RemoveField(
            model_name='supplier_priceline',
            name='hotelid_ppn1',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancelable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancelable_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkindate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkoutdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='refunable_amount',
            field=models.IntegerField(default=0),
        ),
    ]
