# Generated by Django 3.0.6 on 2020-09-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200924_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='refunable_amount',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='refundable_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='cancelationBookingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundable', models.BooleanField(default=False)),
                ('cancelable_hours', models.IntegerField(default=0)),
                ('refundable_amount', models.IntegerField(default=0)),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
            ],
        ),
    ]
