# Generated by Django 3.0.6 on 2020-09-29 04:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200928_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.TextField()),
                ('type', models.TextField()),
                ('display_order', models.IntegerField()),
                ('image_url', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
            options={
                'db_table': 'provider_images',
            },
        ),
    ]
