# Generated by Django 3.0.6 on 2020-10-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200929_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancelable',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancelable_hours',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='checkindate',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='checkoutdate',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='refundable_amount',
        ),
        migrations.DeleteModel(
            name='cancelationBookingPolicy',
        ),
    ]
