# Generated by Django 3.0.6 on 2020-10-01 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201001_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCancellationPolicy',
            fields=[
                ('cancellation_policy_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cancellation_type', models.TextField(choices=[('UNKNOWN_CANCELLATION_POLICY', 'UNKNOWN_CANCELLATION_POLICY'), ('FREE_CANCELLATION', 'FREE_CANCELLATION'), ('NON_REFUNDABLE', 'NON_REFUNDABLE'), ('PARTIAL_REFUND', 'PARTIAL_REFUND')])),
                ('description', models.TextField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('penalty_currency', models.CharField(max_length=3)),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HotelBooking')),
            ],
            options={
                'db_table': 'api_hotel_cancellation_policy',
            },
        ),
    ]
