# Generated by Django 3.0.6 on 2020-10-07 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_hotelcancellationpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMapping',
            fields=[
                ('provider_mapping_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('giata_code', models.TextField()),
                ('provider_code', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
            options={
                'db_table': 'provider_mappings',
            },
        ),
        migrations.DeleteModel(
            name='supplier_hotels',
        ),
        migrations.AddIndex(
            model_name='providermapping',
            index=models.Index(fields=['provider', 'provider_code'], name='provider_ma_provide_ec5dea_idx'),
        ),
    ]
