# Generated by Django 3.0.6 on 2020-10-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201007_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotel_listing',
        ),
        migrations.DeleteModel(
            name='sn_hotel_map',
        ),
        migrations.DeleteModel(
            name='sn_images_map',
        ),
    ]
