# Generated by Django 3.0.6 on 2020-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20201008_0508'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providermapping',
            index=models.Index(fields=['provider', 'giata_code'], name='provider_ma_provide_c4b14a_idx'),
        ),
    ]
