# Generated by Django 3.0.6 on 2020-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20201008_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcancellationpolicy',
            name='begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelcancellationpolicy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelcancellationpolicy',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelcancellationpolicy',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hotelcancellationpolicy',
            name='penalty_currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
