# Generated by Django 3.0.6 on 2020-10-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20201009_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfeatures',
            name='name',
            field=models.TextField(choices=[('enabled_connectors', 'ENABLED_ADAPTERS'), ('test_mode', 'TEST_MODE')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfeatures',
            unique_together={('organization', 'name')},
        ),
    ]
