# Generated by Django 3.1.2 on 2020-10-14 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20201009_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerhotel',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='providerhotel',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerhotel',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='providerhotel',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
