# Generated by Django 3.1.2 on 2020-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201014_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerhotel',
            name='postal_code',
            field=models.TextField(null=True),
        ),
    ]
