# Generated by Django 3.1.2 on 2020-10-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_providerhotel_provider_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supplier_priceline',
        ),
    ]
