# Generated by Django 3.1.2 on 2020-10-21 05:09
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_delete_supplier_priceline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_code',
            new_name='provider_hotel_id',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='simplenight_hotel_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='api.provider'),
        ),
        migrations.RunSQL(
            "UPDATE api_hotel_bookings SET provider_id = providers.id FROM providers "
            "WHERE providers.name = api_hotel_bookings.provider_name"
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='provider_name',
        ),
    ]
