# Generated by Django 3.1.2 on 2020-10-27 05:39
import django_enumfield.db.fields
from django.db import migrations
from django.db.models import CharField

import api.models.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20201027_0529"),
    ]

    operations = [
        migrations.RunSQL("UPDATE payment_transaction SET transaction_type = '0'"),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_type",
            field=django_enumfield.db.fields.EnumField(enum=api.models.models.TransactionType),
        ),
        migrations.AlterField(
            model_name="paymenttransaction", name="payment_token", field=CharField(max_length=128, null=True),
        ),
    ]
