# Generated by Django 3.1.2 on 2020-10-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20201027_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonamealternatename',
            name='is_preferred',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geonamealternatename',
            name='is_short_name',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
