# Generated by Django 3.1.2 on 2020-10-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20201028_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='location_type',
            field=models.TextField(null=True),
        ),
    ]
