# Generated by Django 3.1.2 on 2020-10-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_geoname_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locator', models.CharField(max_length=8)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.booking')),
            ],
        ),
    ]
