# Generated by Django 3.1.2 on 2020-11-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20201101_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationfeatures',
            options={'verbose_name': 'Organization Feature', 'verbose_name_plural': 'Organization Features'},
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='organizationfeatures',
            name='name',
            field=models.TextField(choices=[('enabled_connectors', 'ENABLED_ADAPTERS'), ('test_mode', 'TEST_MODE'), ('stripe_api_key', 'STRIPE_API_KEY')]),
        ),
    ]
