# Generated by Django 3.1.2 on 2020-11-13 19:27
import uuid

import django
import django_enumfield.db.fields
from django.db import migrations, models

import api.models.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_auto_20201106_0201"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderHotelPhones",
            fields=[
                ("provider_hotel_phone_id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("provider_code", models.TextField()),
                ("type", django_enumfield.db.fields.EnumField(enum=api.models.models.PhoneType)),
                ("phone_number", models.TextField()),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.provider")),
            ],
            options={"db_table": "provider_hotel_phones",},
        ),
        migrations.AddIndex(
            model_name="providerhotelphones",
            index=models.Index(fields=["provider", "provider_code"], name="provider_ho_provide_521a46_idx"),
        ),
        migrations.AddField(
            model_name="providerhotelphones",
            name="provider_hotel",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.providerhotel"),
        ),
    ]
