# Generated by Django 3.1.2 on 2020-11-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_auto_20201113_1927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationfeatures",
            name="name",
            field=models.TextField(
                choices=[
                    ("enabled_connectors", "ENABLED_ADAPTERS"),
                    ("test_mode", "TEST_MODE"),
                    ("stripe_api_key", "STRIPE_API_KEY"),
                    ("priceline_api_url", "PRICELINE_API_URL"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="providerhotelphones",
            name="provider_hotel",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="phone", to="api.providerhotel"
            ),
        ),
    ]
