# Generated by Django 3.1.2 on 2020-11-22 07:33

import api.models.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_booking_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('search_event_data_id', models.UUIDField(primary_key=True, serialize=False)),
                ('search_type', django_enumfield.db.fields.EnumField(enum=api.models.models.SearchType)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('search_input', models.TextField()),
                ('result', django_enumfield.db.fields.EnumField(enum=api.models.models.SearchResult)),
                ('elapsed_time', models.IntegerField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization')),
            ],
            options={
                'db_table': 'search_events',
            },
        ),
        migrations.CreateModel(
            name='HotelEvent',
            fields=[
                ('hotel_event_data_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('search_event_data_id', models.TextField()),
                ('provider_code', models.TextField()),
                ('giata_code', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provider')),
            ],
            options={
                'db_table': 'hotel_events',
            },
        ),
    ]
