# Generated by Django 3.1.2 on 2020-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_hotelevent_searchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelevent',
            name='search_event_data_id',
            field=models.UUIDField(),
        ),
    ]
