# Generated by Django 3.1.2 on 2020-12-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_auto_20201207_0538"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchevent", name="request_id", field=models.CharField(max_length=8, null=True),
        ),
    ]
