# Generated by Django 3.1.2 on 2021-01-20 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20210119_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueimage',
            options={'verbose_name': 'Venue Media'},
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='rating',
            new_name='star_rating',
        ),
        migrations.RenameField(
            model_name='venueimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='venueimage',
            old_name='venue',
            new_name='venue_id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('NIGHT_LIFE', 'NIGHT_LIFE'), ('HOTELS', 'HOTELS'), ('CAR_SERVICE', 'CAR_SERVICE'), ('GAS_AND_CHARGING', 'GAS_AND_CHARGING'), ('TOLLS', 'TOLLS'), ('SHOPPINGS', 'SHOPPINGS'), ('THINGS_TO_DO', 'THINGS_TO_DO'), ('DINING', 'DINING'), ('FAST_FOOD', 'FAST_FOOD'), ('COFFEE_AND_TEA', 'COFFEE_AND_TEA')], default='NIGHT_LIFE', max_length=20),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venueimage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
        migrations.AlterModelTable(
            name='venueimage',
            table='venue_media',
        ),
    ]
