# Generated by Django 3.1.2 on 2021-01-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20210120_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='id',
            new_name='venue_id',
        ),
        migrations.RenameField(
            model_name='venuemedia',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
