# Generated by Django 3.1.2 on 2021-01-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_productgroup_productmedia_productsnightlife"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuemedia",
            name="venue_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="api.venue"),
        ),
    ]
