# Generated by Django 3.1.2 on 2021-01-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_auto_20210122_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_media",
                to="api.productsnightlife",
            ),
        ),
        migrations.AlterField(
            model_name="productsnightlife",
            name="venue_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="api.venue"
            ),
        ),
    ]
