# Generated by Django 3.1.2 on 2021-01-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_auto_20210122_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="api.productsnightlife",
            ),
        ),
    ]
