# Generated by Django 3.1.2 on 2021-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_auto_20210122_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="status",
            field=models.BooleanField(default=0),
        ),
    ]
