# Generated by Django 3.1.2 on 2021-01-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_auto_20210123_2314"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productgroup",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="productmedia",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="productsnightlife",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="venue",
            old_name="venue_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="venuecontact",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="venuedetail",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="venuemedia",
            old_name="venue_id",
            new_name="venue",
        ),
    ]
