# Generated by Django 3.1.2 on 2021-01-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_auto_20210126_0513"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="productsnightlife",
            name="product_group_id",
        ),
        migrations.AddField(
            model_name="productmedia",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="api.productsnightlife",
            ),
        ),
        migrations.AddField(
            model_name="productsnightlife",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productsnightlife_requests_modified",
                to="api.productgroup",
            ),
        ),
    ]
