# Generated by Django 3.1.2 on 2021-01-26 22:33

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_auto_20210126_1806"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductHotels",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.TextField()),
                ("description", models.TextField()),
                ("room_size", models.TextField()),
                ("max_guests", models.TextField()),
                ("item_code", models.CharField(blank=True, max_length=200, null=True)),
                ("highlight", models.BooleanField(default=0)),
                ("balcony", models.BooleanField(default=0)),
                ("status", models.BooleanField(default=1)),
                ("room_details", jsonfield.fields.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "product_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.productgroup"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="venue", to="api.venue"
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductHotel",
                "verbose_name_plural": "ProductHotels",
                "db_table": "products_hotel",
            },
        ),
        migrations.CreateModel(
            name="ProductsHotelRoomPricing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rate", jsonfield.fields.JSONField(default=dict)),
                ("taxes", jsonfield.fields.JSONField(default=dict)),
                ("guests", jsonfield.fields.JSONField(default=dict)),
                ("dates", jsonfield.fields.JSONField(default=dict)),
                (
                    "product_hotels",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.producthotels"
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductsHotelRoomPricing",
                "verbose_name_plural": "ProductsHotelRoomPricings",
                "db_table": "products_hotel_room_pricing",
            },
        ),
        migrations.CreateModel(
            name="ProductsHotelRoomDetails",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BEDROOM", "BEDROOM"),
                            ("BATHROOM", "BATHROOM"),
                            ("ENTERTAINMENT", "ENTERTAINMENT"),
                            ("FOODANDDRINK", "BATHROOM"),
                            ("MORE", "MORE"),
                        ],
                        default="BEDROOM",
                        max_length=20,
                    ),
                ),
                (
                    "product_hotels",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.producthotels"
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductsHotelRoomDetails",
                "verbose_name_plural": "ProductsHotelRoomDetails",
                "db_table": "products_hotel_room_details",
            },
        ),
    ]
