# Generated by Django 3.1.2 on 2021-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_producthotels_productshotelroomdetails_productshotelroompricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerhotel",
            name="chain_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerhotel",
            name="chain_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
