# Generated by Django 3.1.2 on 2021-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_auto_20210207_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroup",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producthotel",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producthotelsmedia",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productsnightlife",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productsnightlifemedia",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venuemedia",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
