# Generated by Django 3.1.2 on 2021-02-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_auto_20210210_1537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgroup",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="venue_id", to="api.venue"
            ),
        ),
    ]
