# Generated by Django 3.1.2 on 2021-02-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_auto_20210210_2039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsnightlife",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
