# Generated by Django 3.1.2 on 2021-02-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_auto_20210211_0625"),
        ("api", "0093_auto_20210210_2102"),
    ]

    operations = []
