# Generated by Django 3.1.2 on 2021-02-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_merge_20210212_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producthotelsmedia",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="api.producthotel",
            ),
        ),
    ]
