# Generated by Django 3.1.2 on 2021-02-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_auto_20210212_1707"),
        ("api", "0094_merge_20210212_0653"),
    ]

    operations = []
