# Generated by Django 3.1.2 on 2021-02-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0097_merge_20210215_1113"),
    ]

    operations = [
        migrations.RemoveField(model_name="activitybookingmodel", name="provider_base",),
        migrations.RemoveField(model_name="activitybookingmodel", name="provider_taxes",),
        migrations.RemoveField(model_name="activitybookingmodel", name="total_base",),
        migrations.RemoveField(model_name="activitybookingmodel", name="total_taxes",),
    ]
