# Generated by Django 3.1.2 on 2021-02-15 22:25

from django.db import migrations

from api.activities.adapters.urban import urban_adventures_locations_mapping


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_auto_20210215_2057"),
    ]

    operations = [migrations.RunPython(urban_adventures_locations_mapping.insert_mappings)]
