# Generated by Django 3.1.2 on 2021-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0099_auto_20210215_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuedetail",
            name="payment_method",
            field=models.CharField(
                blank=True, choices=[("Paypal", "Paypal"), ("Applepay", "Applepay")], max_length=20, null=True
            ),
        ),
    ]
