# Generated by Django 3.1.2 on 2021-02-18 20:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20210215_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerimages',
            name='meta_info',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
