# Generated by Django 3.1.2 on 2021-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_auto_20210217_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitybookingmodel",
            name="provider_base",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="activitybookingmodel",
            name="provider_taxes",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="activitybookingmodel",
            name="total_base",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="activitybookingmodel",
            name="total_taxes",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
