# Generated by Django 3.1.2 on 2021-02-17 17:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0101_auto_20210217_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuedetail",
            name="payment_method",
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
