# Generated by Django 3.1.2 on 2021-02-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0102_auto_20210217_1708"),
        ("api", "0100_providerimages_meta_info"),
    ]

    operations = []
